version: '2'

services:
  app_server:
    build: _dev-ops/docker/containers/php7
    volumes:
      - ~/.composer/cache:/var/www/composer-cache-dir
      - .:/project
      - .:/var/www/shopware
    links:
      - app_mysql_master:mysql
    environment:
      TERM: xterm
      COMPOSER_CACHE_DIR: /var/www/composer-cache-dir
    ports:
      - "8089:80"
    networks:
      sw_docker_shopware_blog_env_variables:
        ipv4_address: 10.202.202.30

  app_mysql_master:
    build: _dev-ops/docker/containers/mysql-master
    volumes:
      - ./_dev-ops/docker/_volumes/app-mysql-master-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    networks:
      sw_docker_shopware_blog_env_variables:
        ipv4_address: 10.202.202.40

  app_redis:
    build: _dev-ops/docker/containers/redis
    volumes:
      - ./_dev-ops/docker/_volumes/app-redisdata:/data
    networks:
      sw_docker_shopware_blog_env_variables:
        ipv4_address: 10.202.202.60

networks:
  sw_docker_shopware_blog_env_variables:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.202.202.0/24
        gateway: 10.202.202.1